version: "3.8"

services:
  app:
    image: interface-am-img
    build: .
    container_name: interface-am-v1
    env_file:
      - .env

    
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: interface-tunnel
    restart: always
    command: tunnel --url http://interface-am-v1:8501
    depends_on:
      - app